version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - dataPostgres:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - dataPgAdmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

volumes:
  dataPostgres:
  dataPgAdmin:

networks:
  postgres:
    driver: bridge
