version: '3.7'

services:
  restaurant-service:
    container_name: restaurant-service
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./development.env
    networks:
      - my-network
    command: [sh, -c, "cd /usr/src/app && npm run db:setup && npm run start:dev"]    
    
networks:
  my-network:
    external: true
