export { IRestaurant } from './restaurant.interface';
export { IRestaurantsResponse } from './get-multiple-restaurant-response.interface';
export { IRestaurantDetailResponse } from './get-restaurant-information-response.interface';
export { IRestaurantDetailResponse as IRestaurantResponse } from './get-restaurant-information-response.interface';
export { IRestaurantAddressData } from './get-restaurant-address-data.interface';
export { IFetchRestaurantsOfMerchantResponse } from './fetch-restaurants-of-merchant-response.interface';
export { IFetchRestaurantDetailOfMerchantResponse } from './fetch-restaurant-detail-of-merchant-response.interface';
export { ICreateRestaurantResponse } from './create-restaurant-response.interface';
export { IOrderItemData } from './order-item.interface';
export { IOrderItemToppingData } from './order-item-topping.interface';
export { IGetRestaurantAddressResponse } from './get-restaurant-address-response.interface';
export { IGetMenuItemResponse } from '../../menu/interfaces/get-menuitem-response.interface';
export { IGetInformationForDeliveryResponse } from './get-restaurant-information-to-create-delivery.interface';
export { IGetMetaDataResponse } from './get-meta-data-response.interface';
export { IUpdateFavoriteRestaurantResponse } from './update-favorite-restaurant-response.interface';
