export { IRestaurant } from './restaurant.interface';
export { IRestaurantsResponse } from './get-multiple-restaurant-response.interface';
export { IRestaurantDetailResponse } from './get-restaurant-information-response.interface';
export { IRestaurantDetailResponse as IRestaurantResponse } from './get-restaurant-information-response.interface';
export { IRestaurantAddressData } from './get-restaurant-address-data.interface';
export { IFetchRestaurantsOfMerchantResponse } from './fetch-restaurants-of-merchant-response.interface';
export { IFetchRestaurantDetailOfMerchantResponse } from './fetch-restaurant-detail-of-merchant-response.interface';
export { IIdNameAndPriceData } from './menuitem-name-and-price-data.interface';
export { ICreateRestaurantResponse } from './create-restaurant-response.interface';
export { IOrderItemData } from './order-item.interface';
export { IOrderItemToppingData } from './order-item-topping.interface';
export { IGetRestaurantAddressResponse } from './get-restaurant-address-response.interface';
export { IMenuItemData } from './menuitem-data.interface';
export { IGetMenuItemResponse } from './get-menuitem-response.interface';
